db:
  image: mysql:5.6
  container_name: db
  environment:
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

memcache:
  image: memcached:1.4.24
  container_name: memcache

registrar:
  # Uncomment this line to use the official registrar base image
  image: registrar:v1

  # Uncomment the next two lines to build from a local configuration repo
  #build: ../configuration
  #dockerfile: docker/build/registrar/Dockerfile

  container_name: registrar
  volumes:
    - .:/edx/app/registrar/registrar
  command: /edx/app/registrar/devstack.sh start
  ports:
    - "17344:17344" # TODO: change this to your port
